version: 2.0

jobs:
  build:
    docker:
      - image: quay.io/haskell_works/stack-build-minimal
        environment:
          GIT_AUTHOR_EMAIL: ci@restyled.io
          GIT_AUTHOR_NAME: Restyled.io CI
          GIT_COMMITTER_EMAIL: ci@restyled.io
          GIT_COMMITTER_NAME: Restyled.io CI
    steps:
      - checkout
      - run:
          name: Digest
          command: git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            # yamllint disable-line rule:line-length
            - v1-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "digest" }}
            - v1-{{ .Branch }}-{{ checksum "stack.yaml" }}-
            - v1-{{ .Branch }}
            - v1-
      - run:
          name: Dependencies
          command: |
            make setup
            curl "$HLINT_YAML_SRC" > .hlint.yaml
          environment:
            # yamllint disable-line rule:line-length
            HLINT_YAML_SRC: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
      - run:
          name: Build
          command: make build
      - run:
          name: Lint
          command: make lint
      - save_cache:
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: make test
