references:
  docker-build: &docker-build
    plugins:
      - docker-compose#v3.0.0:
          config: .buildkite/docker-compose.yml
          run: build

  docker-ops: &docker-ops
    plugins:
      - docker-compose#v3.0.0:
          config: .buildkite/docker-compose.yml
          run: ops

steps:
  - label: Build
    command: |
      echo "--- Dependencies"
      make setup setup.lint

      echo "--- Build"
      make build

      echo "--- Test"
      make test

      echo "--- Lint"
      make lint
    <<: *docker-build

  - label: Image
    command: docker build --tag restyled/restyler .
    <<: *docker-ops

  - wait

  - label: Release
    command: |
      echo "--- Pushing image to registry"
      docker tag restyled/restyler \
        quay.io/restyled-io/restyler:bk$BUILDKITE_BUILD_NUMBER
      docker login -u restyled-io+buildkite -p "$QUAY_DOCKER_PASSWORD" quay.io
      docker push quay.io/restyled-io/restyler:bk$BUILDKITE_BUILD_NUMBER

      echo "--- Setting up environment"
      # Unclear why this is required, but it is
      export HEROKU_EMAIL=$HEROKU_EMAIL
      export HEROKU_API_KEY=$HEROKU_API_KEY
      export PUSHOVER_API_KEY=$PUSHOVER_API_KEY
      export PUSHOVER_USER_KEY=$PUSHOVER_USER_KEY

      echo "--- Heroku config:set"
      heroku config:set --app restyled-io \
        "RESTYLER_IMAGE=quay.io/restyled-io/restyler" \
        "RESTYLER_TAG=bk$BUILDKITE_BUILD_NUMBER"

      notify "restyled-io[restyler]" "Deploy of bk$BUILDKITE_BUILD_NUMBER successful"
    branches: master
    <<: *docker-ops
